// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_reached_level_40 = "CgkI0uuioIkOEAIQBQ"; // <GPGSID>
        public const string achievement_reached_level_30 = "CgkI0uuioIkOEAIQBA"; // <GPGSID>
        public const string achievement_cccccombo = "CgkI0uuioIkOEAIQAQ"; // <GPGSID>
        public const string achievement_reached_level_20 = "CgkI0uuioIkOEAIQAw"; // <GPGSID>
        public const string achievement_reached_level_10 = "CgkI0uuioIkOEAIQAg"; // <GPGSID>
        public const string achievement_you_have_logged_on = "CgkI0uuioIkOEAIQBw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkI0uuioIkOEAIQBg"; // <GPGSID>

}

